class FeesPayment {
  // paymentId is optional as it will be auto-generated by the database
  final int? paymentId;
  final String schoolCode;
  final int invoiceId;
  final String? categoryId;
  final DateTime paymentDate;
  final double amountPaid;
  final String modeOfPayment; // ENUM: 'Cash','UPI', 'Card', 'Online', 'Cheque'
  final String referenceNo;
  final String? remarks;
  final String? createdBy;
  final DateTime? createdOn;

  FeesPayment({
    this.paymentId,
    required this.schoolCode,
    required this.invoiceId,
    required this.paymentDate,
    required this.categoryId,
    required this.amountPaid,
    required this.modeOfPayment,
    required this.referenceNo,
    this.remarks,
    this.createdBy,
    this.createdOn
  });

  /// Converts the FeesPayment object to a Map for API submission.
  Map<String, dynamic> toJson() {
    return {
      'school_code': schoolCode,
      'invoice_id': invoiceId,

      // Format date as 'YYYY-MM-DD' for SQL DATE field
      'payment_date': paymentDate.toIso8601String().substring(0, 10),
      'amount_paid': amountPaid.toStringAsFixed(2), // Ensure two decimal places
      'mode_of_payment': modeOfPayment,

      'reference_no': referenceNo,
      'remarks': remarks,
      'created_by': createdBy ?? 'AppUser',
    };
  }

  /// Factory method to create a FeesPayment object from a JSON map (e.g., when fetching from API).
  factory FeesPayment.fromJson(Map<String, dynamic> json) {
    double _toDouble(dynamic value) {
      if (value == null) return 0.0;
      return double.tryParse(value.toString()) ?? 0.0;
    }


      return FeesPayment(
        paymentId: int.tryParse(json['invoice_id']?.toString() ?? ''),
        schoolCode: json['school_code']?.toString() ?? '',
        invoiceId: int.tryParse(json['invoice_id']?.toString() ?? '') ?? 0,

        paymentDate: DateTime.tryParse(
          json['invoice_date']?.toString() ?? '',
        ) ??
            DateTime.now(),

        amountPaid: _toDouble(json['amount_paid']),

        // Optional / not present in response
        modeOfPayment: json['mode_of_payment'].toString(),
        categoryId: json['category_id']?.toString() ?? '0',
        referenceNo: json['reference_no']?.toString() ?? '',
        remarks: json['remarks']?.toString(),
        createdBy: json['created_by']?.toString(),

        createdOn: DateTime.tryParse(
          json['created_on']?.toString() ?? '',
        ) ??
            DateTime.now(),
      );
    }


  }